esphome:
  name: esp-daikin-ctrl

  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
  variant: ESP32C3

# Enable logging
logger:
  level: VERBOSE
  hardware_uart: USB_SERIAL_JTAG
  baud_rate: 2500000

#Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

external_components:
  - source: components

status_led:
    pin: GPIO4

climate:
  - platform: daikin_ducted
    id: daikin0
    name: "Ducted AC"

fan:
  - platform: template
    name: "Ducted Fan"
    speed_count: 3
    on_state:
      then:
        lambda: |-
          auto call = id(daikin0).make_call();
          switch(x->state) {
            case true: call.set_mode("FAN_ONLY"); break;
            case false: call.set_mode("OFF"); break;
          }
          call.perform();
    on_speed_set:
      then:
        lambda: |-
          auto call = id(daikin0).make_call();
          switch(x) {
            case 1: call.set_fan_mode("LOW"); break;
            case 2: call.set_fan_mode("MEDIUM"); break;
            case 3: call.set_fan_mode("HIGH"); break;
            default: break;
          }
          call.perform();